###################################################
#                                                 #
#                  !! WARNING !!                  #
#                                                 #
#Please, DO NOT change anything in version section#
#                                                 #
###################################################
version: 0.1.1-BETA




Prefix: "&e[&bSilky&1Spawner&e] "


#If true, only PICKAXE with enchantment (custom enchantment with CustomEnchantment is true and SilkTouch with false)
#will be able to break and get the spawner. If false, breaker receives nothing with non-enchanted pickaxe
RequireEnchantment: false
BreakMessage: "&cYou can't break this spawner!"


#If true, GameMode listed below will be required if a player want to pick the spawner up. Others gamemode will be received nothing.
Require: true 
GameMode: SURVIVAL
GameModeMessage: "&8Only players in survival mode can break this spawner."


#Name and Lore of the spawner appeared when placing the spawner down. Distance is how far from the Name to the top face of the spawner.
#Spacing stands for is the gap between each line (From 0.1 -> 1 with 1 is a full block height)
NameAndLore:
  Distance: 2.0
  Spacing: 0.3


#Number of characters that can be added to name or lore of the spawner
#Should the plugin counts the color codes as character. For example, &a&lKnightHat has 13 characters if true, and 9 if false
#!!!blank spaces(" ") will not be counted.
CountTheCodes: true
MinimumChars: 3
MaximumChars: 15
# %type% could be either Name or Lore.
InputTooShort: "&bYour %type% is too short. At least 3 characters required"
InputTooLong: "&bYour %type% is too long. Can only be under 15 characters required"
Name: Name
Lore: Lore
#This line will be appeared in lore applied to every spawner on the last line (this line will not be displayed when placed).
TypeOfCreature: "&cCreature: &6&l%creature_type%"


#If true, you can change the message in the message.yml file
CustomEnchantment: true
EnchantmentName: "Spawner Picker"


CancelCommand: "cancel"


#For more color codes. Visit this website: https://www.colorschemer.com/minecraft-color-codes/
HelpCommand:
  Header: "&9List of all &b&lCLICKABLE &9commands"
  HoverText: Click here to get the command!
  TextColor: YELLOW
  HoverColor: GRAY
  
  
CommandsAssistant:
  help:
    Usage: "/silkyspawner help"
    Description: "List all the available commands."
    Permission: 
  reload:
    Usage: "/silkyspawner reload"
    Description: "Reload this plugin."
    Permission: silkyspawner.admin
  enchant:
    Usage: "/silkyspawner enchant"
    Description: "Add custom enchantment to your holding pickaxe"
    Permission: silkyspawner.command.addenchantment
  setname:
    Usage: "/silkyspawner setname <name>"
    Description: "Name your spawner"
    Permission: silkyspawner.command.setname
  lore:
    Usage: "/silkyspawner lore "
    Description: "Get help for lore command"
    Permission: silkyspawner.command.lore
  remove:
    Usage: "/silkyspawner remove <radius>"
    Description: "Remove all the ArmorStands around player."
    Permission: silkyspawner.command.remove
  create:
    Usage: "/silkyspawner create [Mob Type]"
    Description: "Give you a spawner to modify with the specific mob."
    Permission: silkyspawner.command.create
  gui:
    Usage: "/silkyspawner gui"
    Description: "Open GUI instead of using commands"
    Permission: silkyspawner.command.gui