#########################################
#                                       #
#                BUTTONS                #
#                                       #
# Please, DO NOT change anything before #
#       ":" or you will get errors      #
#                                       #
#########################################

YesButton: "&aYes"
NoButton: "&cNo"
NextPageButton: "&7Next page"
PreviousPageButton: "&7Previous Page" 
GoBackButton: "&eGo back"
CloseButton: "&c&lClose Menu"


#########################################
#                                       #
#             CONFIRM MENU              #
#                                       #
# Please, DO NOT change anything before #
#       ":" or you will get errors      #
#                                       #
#########################################

ConfirmMenu:
  Title: "&a&lConfirm Menu"
  FillItem: RED_STAINED_GLASS_PANE
  

#########################################
#                                       #
#          CREATE SPAWNER MENU          #
#                                       #
# Please, DO NOT change anything before #
#       ":" or you will get errors      #
#                                       #
#########################################
  
CreateSpawnerMenu:
  Title: "&a&lCreate &b&lCustom &e&lSpawner &f- &8Page %page%"
  FillItem: BLUE_STAINED_GLASS_PANE
  


#########################################
#                                       #
#               MAIN MENU               #
#                                       #
# Please, DO NOT change anything before #
#       ":" or you will get errors      #
#                                       #
#########################################

MainMenu:
  Title: "&c&lMain &d&lMenu"
  CreateSpawnerItem:
    Name: "&aCreate Spawner"
    Lore:
      - ""
      - "&8Get your own spawner"
      - ""
  SetNameItem: 
    Name: "&bSet Name"
    Lore:
      - ""
      - "&8Name your spawner"
      - ""
  LoreItem:
    Name: "&eLore"
    Lore:
      - ""
      - "&8Something to do with lore"
      - ""
  EnchantPickaxeItem: 
    Name: "&dEnchanting"
    Lore:
      - ""
      - "&8Use it on your pickaxe"
      - ""
  RemoveItem:
    Name: "&4Remove ArmorStands"
    Lore:
      - ""
      - "&8Remove all the AmorStands"
      - "&8within the given radius!"
      - ""
  ReloadItem:
    Name: "&aReload plugin"
    Lore:
      - ""
      - "&8Reload plugin!"
      - ""
  HelpItem:
    Name: "&6Help List"
    Lore:
      - ""
      - "&8List all the available commands"
      - ""
      

#########################################
#                                       #
#        LORE MODIFICATIOR MENU         #
#                                       #
# Please, DO NOT change anything before #
#       ":" or you will get errors      #
#                                       #
#########################################

LoreModificatiorMenu:
  Title: "&d&lLore Modificatior"
  AddLoreButton: "&aAdd lore"
  SetLoreButton: "&bSet lore"
  InsertLoreButton: "&9Insert lore"
  RemoveLoreButton: "&cRemove lore"
  
  
#########################################
#                                       #
#       LINE/RANGE CHOOSING MENU        #
#                                       #
# Please, DO NOT change anything before #
#       ":" or you will get errors      #
#                                       #
#########################################

LineRangeMenu:
  LineTitle: "&aChoose a line to continue"
  LineDisplay: "&eLine#: &6%line%"
  RangeTitle: "&cDefine a range to clear"
  RangeDisplay: "&eRadius: &6%radius%" 
  FillItem: WHITE_STAINED_GLASS_PANE
  
  
#########################################
#                                       #
#          SPAWNER STATUS MENU          #
#                                       #
# Please, DO NOT change anything before #
#       ":" or you will get errors      #
#                                       #
#########################################  

SpawnerModificationMenu:
  Title: "&c&lSpawner's &a&lstatus"
  FillItem: GLASS_PANE 
  Location: "&7Location: &bX:%x% Y:%y% Z:%z%"
  SpawnedType: "Spawning: %creature_type%"
  RequiredRange: "&ePlayer have to stay &6&l%block% &eblocks away"
  Delay: "&aSpawns a mob &bbetween &6%min% &bsecond(s) and &6%max% &bsecond(s)" 